name: tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize] }
  push: { branches: [main] }

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        swift-image:
          - name: swift:5.10-noble
            continue-on-error: false
          - name: swift:6.0-noble
            continue-on-error: false
          - name: swiftlang/swift:nightly-main-jammy
            # https://github.com/swiftlang/swift/issues/77242
            continue-on-error: true
        config:
          - mode: "debug"
            build_args: ""
          - mode: "release"
            build_args: "-Xswiftc -enable-testing"

    runs-on: ubuntu-latest

    container: ${{ matrix.swift-image.name }}

    timeout-minutes: 30

    steps:
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Restore .build
        id: "restore-cache"
        uses: actions/cache/restore@v4
        with:
          path: .build
          # e.g. 'enumerator-macro-debug-build-swiftlang/swift:nightly-6.0-jammy-Linux-c7008df8062ac4d5887ead9e59aa05829e'
          key: "${{ github.event.repository.name }}-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
          restore-keys: "${{ github.event.repository.name }}-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"

      - name: Build ${{ github.event.repository.name }}
        continue-on-error: ${{ matrix.swift-image.continue-on-error }}
        run: swift build --build-tests -c ${{ matrix.config.mode }} ${{ matrix.config.build_args }}

      - name: Cache .build
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "${{ github.event.repository.name }}-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"

      - name: Run tests
        continue-on-error: ${{ matrix.swift-image.continue-on-error }}
        run: swift test --parallel --enable-code-coverage -c ${{ matrix.config.mode }}

      - name: Submit code coverage
        continue-on-error: ${{ matrix.swift-image.continue-on-error }}
        uses: vapor/swift-codecov-action@v0.3
        with:
          build_parameters: "-c ${{ matrix.config.mode }}"
          codecov_token: "${{ secrets.CODECOV_TOKEN }}"
